# NumPy Library

<font color="blue">NumPy stand for “Numerical Python”.</font>  

It is a tool suited for array oriented computing efficiently.

The “numpy array” uses less memory than python list and also the execution time is faster.   

The internal type of numpy array is “ndarray”. 

$A_{m,n} =\begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

In [25]:
import numpy as np

In [26]:
# Matrix of 4 Rows and 3 Columns :
#In NumPy, this 2D matrix has Two axes
#First axis length is 4 and Second axis length is 3 (4L,3L) 

matrixA = np.array([(1,2,3),(4,5,6),(7,2,3),(4,5,6)])
print(matrixA)
print('Shape of Matrix', matrixA.shape)
print('Dimension of Matrix', matrixA.ndim)

[[1 2 3]
 [4 5 6]
 [7 2 3]
 [4 5 6]]
Shape of Matrix (4, 3)
Dimension of Matrix 2


In [27]:
matrixA=np.array(matrixA, np.int8)
print("matrixA = ", matrixA)
print("Type of aVector ", type(matrixA))

matrixA =  [[1 2 3]
 [4 5 6]
 [7 2 3]
 [4 5 6]]
Type of aVector  <class 'numpy.ndarray'>



$v_{m}=\begin{pmatrix}
  v_{1}\\
  v_{2} \\
  \vdots \\
  v_{m}
 \end{pmatrix}$

In [28]:
v = np.array([1,2,3])
v
# v.shape
# v.T
#reshape(3,1) 

array([1, 2, 3])

In [29]:
B=np.array([[10, 4, 9], [2,4,8],[20,4,18],[23, 7, 5]])
B.shape

(4, 3)

### Creating a NumPy array – arange
`arange([start,] stop[, step], [, dtype=None])`  

**arange** returns evenly spaced values within a given interval starting from first optional parameter and within the `stop` value.  
If only one parameter is given, it is assumed as `stop` and the `start` is automatically set to 0.  
If the `step` is not given, it is set to `1` but if `step` is given, the `start` parameter cannot be optional, i.e. it has to be given as well.  
The `step` sets the spacing between two adjacent values of the output array.

In [30]:
dayTemperature=np.arange(6)
#First Value is 0 and it gives output 5 with default interval of 1
print(dayTemperature)

[0 1 2 3 4 5]


In [31]:
dayTemperature=np.arange(6,12, 1)
#First Value is 22 and it stops at 30, So 30 is not included
print(dayTemperature)

[ 6  7  8  9 10 11]


In [32]:
dayTemperature=np.arange(5.3)
#First Value is 0 and it gives output 25 with default interval of 1
print(dayTemperature)

[0. 1. 2. 3. 4. 5.]


In [33]:
dayTemperature=np.arange(2.02, 5.3, 0.25)
#First Value is 2.02 and it gives output 5.27 with default interval of 0.25
print(dayTemperature)
dayTemperature=np.arange(2.02, 5.27, 0.25)
#First Value is 2.02 and it gives output 5.02 with default interval of 0.25
print(dayTemperature)

[2.02 2.27 2.52 2.77 3.02 3.27 3.52 3.77 4.02 4.27 4.52 4.77 5.02 5.27]
[2.02 2.27 2.52 2.77 3.02 3.27 3.52 3.77 4.02 4.27 4.52 4.77 5.02]


### Creating a NumPy array – linspace
`linspace(start, stop, num=50, endpoint=True, retstep=False)`  

<font color='blue'>create NumPy array using linspacebar</font>

Array of linearly spaced values defined by `num` including `start` and `stop`  

<font color='blue'>default value of num is 50</font>


In [34]:
dayTemperature=np.linspace(20,30,11)
print(dayTemperature)

[20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]


In [35]:
dayTemperature, spacing=np.linspace(20,30,11,  endpoint=True, retstep=True)
print(dayTemperature, spacing)

[20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.] 1.0


In [36]:
A=np.arange(12).reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Use `np.random.rand` to create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [37]:
A=np.random.rand(4,3)*100
A

array([[87.92732003,  8.83068649, 52.34474277],
       [29.26596368, 53.11197643, 85.25288063],
       [19.86112156, 98.33498611,  1.10470877],
       [59.26099797, 81.23241149, 56.70627215]])

Use `np.random.randn` to generates an array of given shape, filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.

In [38]:
A=np.random.randn(12).reshape(4,3)
A

array([[-0.63504458, -0.8179718 , -1.63396731],
       [-0.67489551,  0.43604631,  0.0367842 ],
       [ 0.57078953,  0.02535633,  1.17474196],
       [-1.3532692 ,  0.61953775,  1.6774811 ]])

Solve a linear matrix equation, or system of linear scalar equations.

Computes the “exact” solution, `x`, of the well-determined, i.e., full rank, linear matrix equation `ax = b`.

In [40]:
#This code explains the difference between array and matrix with example of 3D State of Stress

stateofStress=np.array([200]).reshape(1,1)

elasticityMatrix=np.array([200000]).reshape(1,1)

stateofStrain=np.linalg.solve(elasticityMatrix, stateofStress)

print("State of Strain ",stateofStrain)

State of Strain  [[0.001]]
