<font color='blue'>    
- Run your cells using SHIFT+ENTER (or "Run cell")

In [1]:
import numpy as np
import math

**Test Code-1**  

Consider random arrays of shape `a(4,3)` and `b(3,2)`. What is the shape of `a*b` and `np.dot(a,b)`?  
`np.dot(a, b)` has shape  = > number of rows of `a`, number of columns of `b` 

- In numpy the `*` operator indicates element-wise multiplication and is different from `np.dot`.
- Dot Product is also known as inner product

In [2]:
a=np.random.randn(4,3)
b=np.random.randn(3,2)
c=a*b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

<span style="color:blue;">To perform element-wise multiplication, the dimension of both the arrays must be the same.</span>

<span style="color:brown">The other method is to broadcating.</span>


In [ ]:
a=np.arange(12).reshape(4,3)
b=np.arange(10,22).reshape(4,3)
c=a*b
print(c)

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]
 [171 200 231]]


In [ ]:
a=np.random.randn(256,15)
b=np.random.randn(15,5)
c=np.dot(a,b)
c.shape

(256, 5)

To perform `dot product` on two muti-dimension arrays, the last dimension of the first array should be equal to last but one dimension of second array. So check `a.shape[-1]==b.shape[-2]`

In [ ]:
print(a.shape[-1], b.shape[-2])
a.shape[-1] == b.shape[-2]

15 15


True

In [ ]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
c=a+b.T
print("Shape of a+b.T ",c.shape)
c=a.T+b
print("Shape of a.T+b ",c.shape)

In [ ]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
print(c)

#### `np.exp`, `np.log`, and `np.reshape`  ####

**sigmoid function, np.exp()**  

Implement `np.exp()` and `math.exp()` for the sigmoid function and compare.  

$$sigmoid(x) = \frac{1}{1+e^{-x}}$$  

<img src="images/Sigmoid.png" style="width:500px;height:228px;text-align:center">

In [ ]:
def sigmoid(z):
  return 1/(1+math.exp(-z))
sigmoid(1)

<span style="color:brown"> **Cannot pass array as an arguement**</span>  

Give it a try to pass array to find sigmoid function of all the array elements.

In [ ]:
def sigmoid(z):
  return 1/(1+np.exp(-z))
sigmoid(1)

0.7310585786300049

In [ ]:
a=np.array([1,2,3])
sigmoid(a)

if x is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.

In [ ]:
b=a+3
b*7

In [ ]:
w = np.array([[0.1124579], [0.23106775]])
b = -0.3
X = np.array([[1., -1.1, -3.2],[1.2, 2., 0.1]])
A=sigmoid(np.dot(w.T,X)+b)
print(A)

[[0.52241976 0.50960677 0.34597965]]


Create an array corresponding to `(px_x*px_y*3)` and reshape to `(px_x, px_y,3)` and use `image.shape[0]`, `image.shape[1]` and `image.shape[2]`  

We can also use `image.reshape(-1,1)` for arranging all elements in a column vector. `-1` represnt unknown rows.  

We can also use `(1,-1)` for unknown columns and one row if required. 

In [ ]:
a=np.random.randn(4*4*3)
image=a.reshape(4,4,3)
image.shape[0]
image.reshape(-1,1)

In [ ]:
image.reshape(1,-1)

Row Normalization is done by dividing each element of row of a given vector x by its norm based on row.  

It is changing x to $ \frac{x}{\| x\|} $.  

We get a column vector of norm if we take the square root of the sum of squares of each row elements. Then divide each row by its norm to normalize rows.


$$\| x\| = \text{np.linalg.norm(x, axis=1, keepdims=True)}$$  

With `keepdims=True` the result will broadcast correctly against the original x.

`axis=1` means you are going to get the norm in a row-wise manner. If you need the norm in a column-wise way, you would need to set `axis=0`. 



In [ ]:
x = np.array([[0, 3, 4],
              [1, 6, 4]])
x_norm=np.linalg.norm(x, axis=1, keepdims=True)
x=x/x_norm
print("Norm ", x_norm, "\nnormalizeRows(x) = ", x)

Norm  [[5.        ]
 [7.28010989]] 
normalizeRows(x) =  [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [ ]:
a=np.array([[1,4, 5],[3,5,8]])  
b=np.sum(a,axis=1)  
b  

array([10, 16])

In [ ]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum=np.sum(x_exp, axis=1).reshape(x.shape[0],1)
    s=x_exp/x_sum    
    return s

In [ ]:
x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
s=softmax(x)
print(s)

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [ ]:
import time

x1 = np.arange(10000)
x2 = np.arange(10000)

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print ("dot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")


dot ----- Computation time = 7.6979999999995385ms
dot ----- Computation time = 0.26599999999987745ms


In [ ]:
### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # we create a len(x1)*len(x2) matrix with only zeros

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()
print ("outer = ----- Computation time = " + str(1000 * (toc - tic)) + "ms")
### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer =  ----- Computation time = " + str(1000 * (toc - tic)) + "ms")


outer = ----- Computation time = 59806.299ms
outer =  ----- Computation time = 497.9009999999988ms


In [ ]:
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()
print ("elementwise multiplication  ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication ----- Computation time = " + str(1000*(toc - tic)) + "ms")


elementwise multiplication  ----- Computation time = 10.101999999989175ms
elementwise multiplication ----- Computation time = 0.24199999998586463ms


In [ ]:
### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
#print(W)
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print ("gdot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")
### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

gdot ----- Computation time = 24.57800000001953ms
gdot ----- Computation time = 0.47899999998435305ms


Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. As a reminder, if $x = [x_1, x_2, ..., x_n]$, then `np.dot(x,x)` = $\sum_{j=0}^n x_j^{2}$. 

- L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [ ]:
def L2(yhat, y):    
    loss = np.dot(abs(y-yhat).T, abs(y-yhat))
    return loss

In [ ]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat, y)))


L2 = 0.43
