<font color='blue'>    
- Run your cells using SHIFT+ENTER (or "Run cell")

In [1]:
import numpy as np

In [25]:
a = np.array([[0, 1], [1, 0]])
eigenValues, eigenVector=np.linalg.eig(a)
print('Eigen Values = ',eigenValues)
print('Eigen Vector = ',np.round(eigenVector,2))

Eigen Values =  [ 1. -1.]
Eigen Vector =  [[ 0.71 -0.71]
 [ 0.71  0.71]]


In [26]:
A = np.matrix([[1,3,7],[2,8,3],[7,8,1]])
rank=np.linalg.matrix_rank(A)
print('Rank of Matrix = ',rank)

Rank of Matrix =  3


In [27]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))


print('Vertical Append:', np.vstack((f, g)))

a = np.array([[1,1,2], [2,2,3], [4,3,3]])
b = np.array([[5,1,2], [6,2,3], [7,3,4]])
stack=np.vstack((a,b))
print('Vertical Stack', stack)
print(stack[5][0])

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]
Vertical Stack [[1 1 2]
 [2 2 3]
 [4 3 3]
 [5 1 2]
 [6 2 3]
 [7 3 4]]
7


**Test Code-1**  

Consider random arrays of shape `a(4,3)` and `b(3,2)`. What is the shape of `a*b` and `np.dot(a,b)`?  
`np.dot(a, b)` has shape  = > number of rows of `a`, number of columns of `b` 

- In numpy the `*` operator indicates element-wise multiplication and is different from `np.dot`.
- Dot Product is also known as inner product

In [28]:
a=np.random.randn(4,3)
b=np.random.randn(3,2)
c=a*b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

<span style="color:blue;">To perform element-wise multiplication, the dimension of both the arrays must be the same.</span>

<span style="color:brown">The other method is to broadcating.</span>


In [3]:
a=np.arange(12).reshape(4,3)
b=np.arange(10,22).reshape(4,3)
c=a*b
print(c)

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]
 [171 200 231]]


In [4]:
a=np.random.randn(256,15)
b=np.random.randn(15,5)
c=np.dot(a,b)
c.shape

(256, 5)

To perform `dot product` on two muti-dimension arrays, the last dimension of the first array should be equal to last but one dimension of second array. So check `a.shape[-1]==b.shape[-2]`

In [5]:
print(a.shape[-1], b.shape[-2])
a.shape[-1] == b.shape[-2]

15 15


True

In [6]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
c=a+b.T
print("Shape of a+b.T ",c.shape)
c=a.T+b
print("Shape of a.T+b ",c.shape)

Shape of a+b.T  (3, 4)
Shape of a.T+b  (4, 3)


In [7]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
print(c)

[[-5.29450243e-04 -1.82183019e-03  1.26914199e-03]
 [ 4.32625320e-01 -4.65764045e-01  6.46491122e-01]
 [ 9.37303636e-01  6.85062379e-01  1.82907971e-01]]


if x is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.

In [11]:
b=a+3
b*7

array([28, 35, 42])

Create an array corresponding to `(px_x*px_y*3)` and reshape to `(px_x, px_y,3)` and use `image.shape[0]`, `image.shape[1]` and `image.shape[2]`  

We can also use `image.reshape(-1,1)` for arranging all elements in a column vector. `-1` represnt unknown rows.  

We can also use `(1,-1)` for unknown columns and one row if required. 

In [13]:
a=np.random.randn(4*4*3)
image=a.reshape(4,4,3)
image.shape[0]
image.reshape(-1,1)

array([[-1.16799477],
       [-0.58893069],
       [-0.90660539],
       [-0.68788714],
       [-0.83764097],
       [-1.38417142],
       [ 1.40963876],
       [ 0.20813389],
       [ 0.2951316 ],
       [-0.3229349 ],
       [ 1.3984917 ],
       [-0.20028887],
       [-0.97806304],
       [ 1.99400492],
       [ 0.96397364],
       [ 1.38129039],
       [-1.3843951 ],
       [-0.88181871],
       [ 0.72530893],
       [ 0.14983863],
       [ 0.2906824 ],
       [ 0.84480902],
       [ 0.19955682],
       [ 1.07470888],
       [ 0.50523501],
       [ 0.9327927 ],
       [ 0.59590051],
       [ 0.42717952],
       [-0.32313798],
       [-0.16382886],
       [-0.38620066],
       [-0.63884094],
       [ 0.11859829],
       [ 1.51672749],
       [-0.27991934],
       [-1.35615153],
       [ 0.57710436],
       [ 1.23968548],
       [-1.33396648],
       [-0.8144224 ],
       [-0.08662021],
       [ 0.10213372],
       [ 0.44285093],
       [ 0.59492376],
       [ 0.13049952],
       [-0

In [14]:
image.reshape(1,-1)

array([[-1.16799477, -0.58893069, -0.90660539, -0.68788714, -0.83764097,
        -1.38417142,  1.40963876,  0.20813389,  0.2951316 , -0.3229349 ,
         1.3984917 , -0.20028887, -0.97806304,  1.99400492,  0.96397364,
         1.38129039, -1.3843951 , -0.88181871,  0.72530893,  0.14983863,
         0.2906824 ,  0.84480902,  0.19955682,  1.07470888,  0.50523501,
         0.9327927 ,  0.59590051,  0.42717952, -0.32313798, -0.16382886,
        -0.38620066, -0.63884094,  0.11859829,  1.51672749, -0.27991934,
        -1.35615153,  0.57710436,  1.23968548, -1.33396648, -0.8144224 ,
        -0.08662021,  0.10213372,  0.44285093,  0.59492376,  0.13049952,
        -0.99431241,  0.25270594,  0.13140062]])

In [16]:
a=np.array([[1,4, 5],[3,5,8]])  
b=np.sum(a,axis=1)  
b  

array([10, 16])

In [19]:
import time

x1 = np.arange(10000)
x2 = np.arange(10000)

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print ("dot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")


dot ----- Computation time = 3.8689999999999003ms
dot ----- Computation time = 0.5660000000000664ms


In [20]:
### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # we create a len(x1)*len(x2) matrix with only zeros

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()
print ("outer = ----- Computation time = " + str(1000 * (toc - tic)) + "ms")
### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer =  ----- Computation time = " + str(1000 * (toc - tic)) + "ms")


outer = ----- Computation time = 65020.395000000004ms
outer =  ----- Computation time = 456.3930000000056ms


In [21]:
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()
print ("elementwise multiplication  ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication ----- Computation time = " + str(1000*(toc - tic)) + "ms")


elementwise multiplication  ----- Computation time = 5.846000000005347ms
elementwise multiplication ----- Computation time = 0.32199999999704687ms


In [22]:
### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
#print(W)
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print ("gdot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")
### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

gdot ----- Computation time = 24.218000000004736ms
gdot ----- Computation time = 0.2709999999979118ms


Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. As a reminder, if $x = [x_1, x_2, ..., x_n]$, then `np.dot(x,x)` = $\sum_{j=0}^n x_j^{2}$. 

- L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [23]:
def L2(yhat, y):    
    loss = np.dot(abs(y-yhat).T, abs(y-yhat))
    return loss

In [24]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat, y)))


L2 = 0.43
